### ISSUE TITLE
Modifying Code to Transfer Without Software fix documentation

### ISSUE THREAD

**Issue by olesav** [Signiant/web-transfer-api-samples#4]
Please, fix documentation about Uploading/Downloading Without Software.

Current Documentation:
var uploadObject = new Signiant.Mst.NoSoftwareUpload();
# or for downloads:
var downloadObject = new Signiant.Mst.NoSoftwareDownload();

Correct Documentation:

var uploadObject = new Signiant.Mst.NoSoftware.Upload();
# or for downloads:
var downloadObject = new Signiant.Mst.NoSoftware.Download();

**Comment by akfab3** [comment]
Documentation for initializing transfers for "No Client Software" transfers was added and is accessible linking to "Transfer Without Installed Software" from the main "Web Transfer API" page, which links to: http://developer.signiant.com/transferapi/nosoftware.html#modifying-code-to-transfer-without-software
